name: Playground Workflow

on:
  workflow_dispatch:
    inputs: {}

jobs:
  play:
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        shell: bash

    steps:
      - name: play
        run: |
          set -ex
          echo "HOME: $HOME"
          echo "PATH: $PATH"
          env
          ls -alh /dev
          ls -alh /usr/bin
          ls -alh /usr/sbin
          sudo apt-get update -qq
          sudo apt-get install -y qemu-system-arm qemu-efi-aarch64
          lscpu
          qemu-system-aarch64 -accel help
          qemu-system-aarch64 -machine virt -cpu host -accel kvm
